export const PROPERTY_ADD_SUCCESS = 'PROPERTY_ADD_SUCCESS';
export const PROPERTY_ADD_FAIL = 'PROPERTY_ADD_FAIL';

export const PROPERTY_LIST_SUCCESS = 'PROPERTY_LIST_SUCCESS';
export const PROPERTY_LIST_FAIL = 'PROPERTY_LIST_FAIL';

export const PROPERTY_DETAILS_SUCCESS = 'PROPERTY_DETAILS_SUCCESS';
export const PROPERTY_DETAILS_FAIL = 'PROPERTY_DETAILS_FAIL';

export const PROPERTY_SEARCH_SUCCESS = "PROPERTY_SEARCH_SUCCESS";
export const PROPERTY_SEARCH_FAIL = "PROPERTY_SEARCH_FAIL";

export const PROPERTY_EDIT_SUCCESS = 'PROPERTY_EDIT_SUCCESS';
export const PROPERTY_EDIT_FAIL = 'PROPERTY_EDIT_FAIL';

export const PROPERTY_DELETE_SUCCESS = 'PROPERTY_DELETE_SUCCESS';
export const PROPERTY_DELETE_FAIL = 'PROPERTY_DELETE_FAIL';
