export const PROPERTY_ADD_SUCCESS = 'PROPERTY_ADD_SUCCESS';
export const PROPERTY_ADD_FAIL = 'PROPERTY_ADD_FAIL';

export const PROPERTY_LIST_SUCCESS = 'PROPERTY_LIST_SUCCESS';
export const PROPERTY_LIST_FAIL = 'PROPERTY_LIST_FAIL';